/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Pago_en_Linea extends javax.swing.JFrame {

    /**
     * Creates new form Pago_en_Linea
     */
    public Pago_en_Linea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        boton_flecha_adelante1 = new javax.swing.JButton();
        boton_flecha_atras1 = new javax.swing.JButton();
        boton_home1 = new javax.swing.JButton();
        refresh1 = new javax.swing.JButton();
        boton_buscar1 = new javax.swing.JButton();
        texto_buscar1 = new javax.swing.JTextField();
        cobros_s_a1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnModuloImpuestos2 = new javax.swing.JButton();
        btnModuloRecargos2 = new javax.swing.JButton();
        btnModuloCuenta2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnModuloPagos2 = new javax.swing.JButton();
        btnModuloPropietarios2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnModuloRecargos3 = new javax.swing.JButton();
        btnModuloRecargos4 = new javax.swing.JButton();
        btnModuloRecargos5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(181, 218, 238));
        background.setPreferredSize(new java.awt.Dimension(1500, 850));
        background.setRequestFocusEnabled(false);
        background.setVerifyInputWhenFocusTarget(false);
        background.setLayout(null);

        boton_flecha_adelante1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha_derecha.png"))); // NOI18N
        boton_flecha_adelante1.setBorder(null);
        boton_flecha_adelante1.setBorderPainted(false);
        boton_flecha_adelante1.setContentAreaFilled(false);
        boton_flecha_adelante1.setFocusPainted(false);
        boton_flecha_adelante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_flecha_adelante1ActionPerformed(evt);
            }
        });
        background.add(boton_flecha_adelante1);
        boton_flecha_adelante1.setBounds(90, 60, 60, 60);

        boton_flecha_atras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flecha_izq (1).png"))); // NOI18N
        boton_flecha_atras1.setBorder(null);
        boton_flecha_atras1.setBorderPainted(false);
        boton_flecha_atras1.setContentAreaFilled(false);
        boton_flecha_atras1.setFocusPainted(false);
        boton_flecha_atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_flecha_atras1ActionPerformed(evt);
            }
        });
        background.add(boton_flecha_atras1);
        boton_flecha_atras1.setBounds(20, 60, 60, 60);

        boton_home1.setBackground(java.awt.SystemColor.desktop);
        boton_home1.setForeground(new java.awt.Color(240, 240, 240));
        boton_home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        boton_home1.setBorder(null);
        boton_home1.setBorderPainted(false);
        boton_home1.setContentAreaFilled(false);
        boton_home1.setFocusPainted(false);
        boton_home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_home1ActionPerformed(evt);
            }
        });
        background.add(boton_home1);
        boton_home1.setBounds(250, 60, 60, 60);

        refresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresh (1).png"))); // NOI18N
        refresh1.setBorder(null);
        refresh1.setBorderPainted(false);
        refresh1.setContentAreaFilled(false);
        refresh1.setFocusPainted(false);
        background.add(refresh1);
        refresh1.setBounds(170, 60, 60, 60);

        boton_buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        boton_buscar1.setBorder(null);
        boton_buscar1.setBorderPainted(false);
        boton_buscar1.setContentAreaFilled(false);
        boton_buscar1.setFocusPainted(false);
        background.add(boton_buscar1);
        boton_buscar1.setBounds(995, 65, 60, 60);

        texto_buscar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        texto_buscar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        background.add(texto_buscar1);
        texto_buscar1.setBounds(730, 70, 320, 50);

        cobros_s_a1.setFont(new java.awt.Font("Baskerville Old Face", 0, 60)); // NOI18N
        cobros_s_a1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cobros_s_a1.setText("COBROS S.A.");
        background.add(cobros_s_a1);
        cobros_s_a1.setBounds(340, 10, 380, 60);

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        background.add(jButton6);
        jButton6.setBounds(920, 10, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen_top.jpg"))); // NOI18N
        background.add(jLabel2);
        jLabel2.setBounds(-420, 0, 1500, 140);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel1.setText("Consulta de Obligaciones");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(30, 20, 440, 30);

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel4.setText("Consultar por:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 60, 300, 24);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField2);
        jTextField2.setBounds(480, 100, 280, 30);

        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jButton1.setText("Consultar");
        jPanel4.add(jButton1);
        jButton1.setBounds(480, 170, 150, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Le recordamos que el descuento por el  pago del impuesto predial urbano \ndesde el 16 al 31 de mayo del 2023 es del 2%.");
        jTextArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(480, 260, 490, 100);

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel6.setText("Ingrese su Número de Predio:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(480, 60, 300, 24);

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Persona.png"))); // NOI18N
        jButton2.setText("Apellidos y nombres");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(20, 100, 350, 60);

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Predio.png"))); // NOI18N
        jButton3.setText("Numero de Predio");
        jPanel4.add(jButton3);
        jButton3.setBounds(20, 160, 350, 60);

        jButton4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Orden.png"))); // NOI18N
        jButton4.setText("Orden para el Pago");
        jPanel4.add(jButton4);
        jButton4.setBounds(20, 220, 350, 60);

        jButton5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton5.setText("Consulta tu Cédula catastral");
        jPanel4.add(jButton5);
        jButton5.setBounds(220, 300, 230, 80);

        background.add(jPanel4);
        jPanel4.setBounds(20, 270, 1020, 400);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setText("2023 Cobros S.A.");
        background.add(jLabel3);
        jLabel3.setBounds(910, 680, 140, 21);

        jPanel1.setBackground(new java.awt.Color(99, 184, 148));

        btnModuloImpuestos2.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        btnModuloImpuestos2.setText("Impuestos");
        btnModuloImpuestos2.setBorder(null);
        btnModuloImpuestos2.setBorderPainted(false);
        btnModuloImpuestos2.setContentAreaFilled(false);
        btnModuloImpuestos2.setFocusable(false);

        btnModuloRecargos2.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        btnModuloRecargos2.setText("Recargos");
        btnModuloRecargos2.setBorder(null);
        btnModuloRecargos2.setBorderPainted(false);
        btnModuloRecargos2.setContentAreaFilled(false);
        btnModuloRecargos2.setFocusable(false);

        btnModuloCuenta2.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        btnModuloCuenta2.setText("Mi Cuenta");
        btnModuloCuenta2.setBorder(null);
        btnModuloCuenta2.setBorderPainted(false);
        btnModuloCuenta2.setContentAreaFilled(false);
        btnModuloCuenta2.setFocusable(false);

        jPanel2.setBackground(new java.awt.Color(64, 149, 113));

        btnModuloPagos2.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        btnModuloPagos2.setText("Pagos");
        btnModuloPagos2.setBorder(null);
        btnModuloPagos2.setBorderPainted(false);
        btnModuloPagos2.setContentAreaFilled(false);
        btnModuloPagos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloPagos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnModuloPagos2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModuloPagos2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnModuloPropietarios2.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        btnModuloPropietarios2.setText("Propietarios");
        btnModuloPropietarios2.setBorder(null);
        btnModuloPropietarios2.setBorderPainted(false);
        btnModuloPropietarios2.setContentAreaFilled(false);
        btnModuloPropietarios2.setFocusable(false);
        btnModuloPropietarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloPropietarios2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnModuloPropietarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(613, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 462, Short.MAX_VALUE)
                    .addComponent(btnModuloImpuestos2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btnModuloRecargos2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(btnModuloCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 18, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuloPropietarios2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnModuloImpuestos2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModuloRecargos2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModuloCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        background.add(jPanel1);
        jPanel1.setBounds(0, 200, 1070, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha_dere_sin (1).png"))); // NOI18N
        jLabel10.setFocusable(false);
        background.add(jLabel10);
        jLabel10.setBounds(130, 160, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha_dere_sin (1).png"))); // NOI18N
        jLabel5.setFocusable(false);
        background.add(jLabel5);
        jLabel5.setBounds(260, 160, 30, 30);

        btnModuloRecargos3.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        btnModuloRecargos3.setText("Pago en linea");
        btnModuloRecargos3.setBorder(null);
        btnModuloRecargos3.setBorderPainted(false);
        btnModuloRecargos3.setContentAreaFilled(false);
        btnModuloRecargos3.setFocusable(false);
        btnModuloRecargos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloRecargos3ActionPerformed(evt);
            }
        });
        background.add(btnModuloRecargos3);
        btnModuloRecargos3.setBounds(290, 155, 200, 40);

        btnModuloRecargos4.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        btnModuloRecargos4.setText("Home");
        btnModuloRecargos4.setBorder(null);
        btnModuloRecargos4.setBorderPainted(false);
        btnModuloRecargos4.setContentAreaFilled(false);
        btnModuloRecargos4.setFocusable(false);
        btnModuloRecargos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloRecargos4ActionPerformed(evt);
            }
        });
        background.add(btnModuloRecargos4);
        btnModuloRecargos4.setBounds(20, 155, 110, 40);

        btnModuloRecargos5.setFont(new java.awt.Font("Baskerville Old Face", 0, 36)); // NOI18N
        btnModuloRecargos5.setText("Pagos");
        btnModuloRecargos5.setBorder(null);
        btnModuloRecargos5.setBorderPainted(false);
        btnModuloRecargos5.setContentAreaFilled(false);
        btnModuloRecargos5.setFocusable(false);
        btnModuloRecargos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloRecargos5ActionPerformed(evt);
            }
        });
        background.add(btnModuloRecargos5);
        btnModuloRecargos5.setBounds(150, 155, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_flecha_adelante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_flecha_adelante1ActionPerformed
        Modulo_Impuestos mi =new Modulo_Impuestos();
        mi.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_flecha_adelante1ActionPerformed

    private void boton_flecha_atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_flecha_atras1ActionPerformed
        Modulo_Pagos mps =new Modulo_Pagos();
        mps.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_flecha_atras1ActionPerformed

    private void boton_home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_home1ActionPerformed
        Back bk =new Back();
        bk.setVisible(true);
        dispose();
    }//GEN-LAST:event_boton_home1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnModuloPagos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloPagos2ActionPerformed
        Modulo_Pagos abrir = new Modulo_Pagos();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloPagos2ActionPerformed

    private void btnModuloPropietarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloPropietarios2ActionPerformed
        Modulo_Propietarios abrir = new Modulo_Propietarios();
        abrir.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnModuloPropietarios2ActionPerformed

    private void btnModuloRecargos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloRecargos3ActionPerformed
        
    }//GEN-LAST:event_btnModuloRecargos3ActionPerformed

    private void btnModuloRecargos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloRecargos4ActionPerformed
        Back abrir = new Back();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloRecargos4ActionPerformed

    private void btnModuloRecargos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloRecargos5ActionPerformed
        Modulo_Pagos abrir = new Modulo_Pagos();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloRecargos5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pago_en_Linea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pago_en_Linea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pago_en_Linea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pago_en_Linea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pago_en_Linea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton boton_buscar1;
    private javax.swing.JButton boton_flecha_adelante1;
    private javax.swing.JButton boton_flecha_atras1;
    private javax.swing.JButton boton_home1;
    private javax.swing.JButton btnModuloCuenta2;
    private javax.swing.JButton btnModuloImpuestos2;
    private javax.swing.JButton btnModuloPagos2;
    private javax.swing.JButton btnModuloPropietarios2;
    private javax.swing.JButton btnModuloRecargos2;
    private javax.swing.JButton btnModuloRecargos3;
    private javax.swing.JButton btnModuloRecargos4;
    private javax.swing.JButton btnModuloRecargos5;
    private javax.swing.JLabel cobros_s_a1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton refresh1;
    private javax.swing.JTextField texto_buscar1;
    // End of variables declaration//GEN-END:variables
}
